public/js/Get_allRow.js, public/js/Send_Row.js, resources/js/Get_allRow.js, resources/js/Send_Row.js
- #19 
- #17
- バグの改善
- #17
にて，不要箇所だと判断した場所は必要な箇所で，コンパイルのし忘れなだけでした
- 不要だと削除したコードを戻した
- `name`など，本当に不要な箇所を削除
- **コンパイル**
無し
- 掲示板が利用可能になる
- 無し
- 掲示板への書き込み・過去の書き込みの表示を動作確認
正常に動作しました
- コンパイル忘れに気を付けましょう
=> 不要箇所だと削除した場所は必要でした

public/js/Get_allRow.js, resources/js/Get_allRow.js
- #24 
- 無し
- 掲示板の自動更新機能の再生
- なし
- 掲示板を手動で更新しなくても一定時間ごとに自動で更新される様になる
- 無し
- 初回読み込みの速度が速くなっている事を確認した
- 自身の書き込みが自動で更新される事を確認した
- 自分以外の書き込みが自動で更新される事を確認した
- 無し
=> 掲示板自動の自動更新機能の再生

docs/setup.md
- ドキュメント
- プロジェクトをクローンしてから環境構築までが少し複雑なので
- プロジェクトのクローンからページが動作するまでの手順をdocs/setup.mdファイルに記述
- 無し
- 無し
- 無し
- 無し
- 変更があり次第，更新していきます
=> 環境構築手順ファイルの作成

docs/setup.md
- #33 
- #34 
- スレッド（テーブル）作成機能の追加
- スレッド情報記録のテーブルをmigrationで作成可能に
以上の事からドキュメント内にあるテーブル作成の手順が不要になったため，setupドキュメントの修正を行います
- ドキュメント更新日時の変更
- 不要箇所の削除
- 誤字の修正
無し
無し
無し
無し
無し
=> テーブル作成がmigrationで完結するようになったため，ドキュメントの更新

app/Http/Controllers/jQuery_ajax.php, app/Models/Get.php, public/js/app_jquery.js, resources/js/Get_allRow.js
- #41 
無し
- URLが存在しない`thread_id`に編集された場合でもLaravelのエラーが表示されないように
- 上記の場合，掲示板の書き込み表示欄にメッセージを表示
無し
- 無し
- URLの`thread_id`を編集した場合にLaravelのエラーメッセージを表示させられなくなる（正常動作）
- URLの`thread_id`欄に存在しないテーブル名を入力した際にLaravelのエラーが発生しないことを確認
無し
=> 掲示板にアクセスするURLが編集された場合の例外処理

database/migrations/2022_05_05_112244_create_hub_table.php
- #61 
- 無し
- hubテーブルに不足していたカラムを追加
- 無し
- スレッド作成が出来る様になる
- 無し
- スレッドが作成出来る事を確認した
- 無し
=> カラムを追加・スレッド作成機能再生

app/Http/Controllers/jQuery_ajax.php, app/Http/Controllers/keizibanCTL.php, app/Models/Get.php, public/css/app.css, public/js/app_jquery.js, resources/js/Get_allRow.js
- #56 
無し
- ログインしているユーザがいいねを押しているかをメッセージごとに取得
- いいねが押されていればボタンの色を黒色に・そうでなければ白色に
無し
自分が書き込みに対して過去にいいねを押したかをすぐに分かるようになる
無し
- ユーザごとにいいね状態が表示されている事を確認
- 新たに書き込みを行い，上記の動作を確認
- 新たにスレッドを作成し，上記の動作を確認
無し
=> いいねを押していたらボタンの色が黒色に

.gitignore, .vscode/extensions.json, .vscode/settings.json, resources/views/dashboard.blade.php, resources/views/keiziban.blade.php, resources/views/welcome.blade.php
なし
- Twitterのタイムラインをページ内に表示することでページ移動することなく視認できるから
- .vscode/extensions.json  推奨拡張機能を記述
- .vscode/settings.json  設定の共有と *.blade.php をhtmlモードで作業する
- resources/views/keiziban.blade.php  cssの修正とコードフォーマット
- resources/views/welcome.blade.php  アイコンの追加、ダークモードを一時的に無効
- resources/views/dashboard.blade.php  タイムラインの表示、アイコンの追加、ダークモードを一時的に無効、レスポンシブに対応
なし
- 視認性が良くなる
- スマホでも表示が崩れなくなった
- Twitterがすぐ見れる
なし
開発用サーバーにアクセス
なし
=> Twitterタイムラインの表示と部分的なレスポンシブに対応

app/Admin/Controllers/UserController.php, app/Http/Kernel.php, app/Http/Middleware/IsAdmin.php, app/Http/Middleware/PostAccess_only.php, public/js/app_jquery.js, resources/js/Delete_message.js, resources/js/Delete_thread.js, resources/js/Edit_thread.js, resources/js/Restore_message.js, routes/web.php
無し
- 不具合を修正するため
- セキュリティの強化
- 管理者ページにて不足カラムを追加
- `routes/web.php`にてデータ処理のルートメソッドをまとめる
- 管理者ユーザのみの処理を表示するページだけでなく，データ処理自体に管理者ユーザを要求することでセキュリティ強化
（管理者ユーザのみの処理に管理者ユーザかを判断するミドルウェアを追加）
無し
無し
無し
- 一般ユーザで全てのデータ処理URLにPOST, GETメソッドそれぞれでアクセスし，POSTでは期待通り動作する事を，GETでは404エラーが返される事を確認
- 一般ユーザで管理者ユーザのみのURLにGETメソッドでアクセスし，403が返される事を確認
- 管理者ユーザで全てのデータ処理URLにPOST, GETメソッドそれぞれでアクセスし，POSTでは期待通り動作する事を，GETでは404エラーが返される事を確認
無し
=> 不具合修正・コード改良・セキュリティ強化

public/js/app_jquery.js, resources/js/Get_allRow.js, resources/views/MyPage.blade.php, resources/views/auth/login.blade.php, resources/views/auth/register.blade.php, resources/views/dashboard.blade.php, resources/views/hub.blade.php, resources/views/keiziban.blade.php, resources/views/navigation-menu.blade.php, resources/views/policy.blade.php, resources/views/profile/delete-user-form.blade.php, resources/views/profile/logout-other-browser-sessions-form.blade.php, resources/views/profile/show.blade.php, resources/views/profile/two-factor-authentication-form.blade.php, resources/views/profile/update-password-form.blade.php, resources/views/profile/update-profile-information-form.blade.php, resources/views/terms.blade.php, resources/views/welcome.blade.php, webpack.mix.js
無し
- viewファイルでデザインする場所や変更してほしくない箇所をわかりやすくするため
- `resources/js/Get_allRow.js`
- `resources/views/MyPage.blade.php`
- `resources/views/auth/login.blade.php`
- `resources/views/auth/register.blade.php`
- `resources/views/dashboard.blade.php`
- `resources/views/hub.blade.php`
- `resources/views/keiziban.blade.php`
- `resources/views/navigation-menu.blade.php`
- `resources/views/policy.blade.php`
- `resources/views/profile/delete-user-form.blade.php`
- `resources/views/profile/logout-other-browser-sessions-form.blade.php`
- `resources/views/profile/show.blade.php`
- `resources/views/profile/tow-factor-authentication-form.blade.php`
- `resources/views/profile/update-password-form.blade.php`
- `resources/views/profile/update-profile-information-form.blade.php`
- `resources/views/terms.blade.php` …
=> よく表示される（要デザイン）ファイルにコメント追加

resources/views/auth/login.blade.php, resources/views/auth/register.blade.php
なし
見やすいから
デザインの変更
なし
なし
なし
なし
なし
=> ログインと登録フォームのデザインを変更

resources/views/dashboard.blade.php, resources/views/layouts/app.blade.php, resources/views/navigation-menu.blade.php
bootstrapをuser.themeの値によってノーマルモード、ダークモードどちらにするのかを変更するためにこの変更を行った。
headタグ内にbootstarap(darkmode)を追加
ダークモード、ノーマルモードを変更できる。
このダークモード機能追加は始まったばかりでこれから適用できるようにファイルを変更していきます。
=> bootstrapのdarkmode適用のための編集

docs/dev/Docker.md
なし
ファイルのパスが違っていたため
Readme修正
なし
なし
なし
なし
なし
=> ファイルのパスを修正

app/Http/Livewire/Dashboard/Various.php, composer.json, composer.lock, resources/views/dashboard/various.blade.php
- #130 
- なし
- 週間アクセスランキングの追加
- なし
- 週間アクセスランキングを見る事が出来る様になる
- なし
- 1週間以内のアクセスランキングは確認しづらいため，1日以内かそれ以外かのアクセスランキングを取得し，それが正常に動作している事を確認
無し
=> 週間アクセスランキング追加

app/Http/Livewire/Dashboard/Rankings.php, app/Http/Livewire/Dashboard/Threads.php, public/js/app_jquery.js, resources/js/dashboard/Search_thread.js, resources/views/dashboard/threads.blade.php
- #90 
無し
- スレッドの検索機能追加
- 大枠カテゴリで絞り込んだ上での検索機能追加
- 詳細カテゴリで絞り込んだ上での検索機能追加
- 検索の動作がおかしい部分があるが修正方法が分からないのと，大体は出来ているため修正は行いません
- スレッドの検索が出来る様になる
- 大枠カテゴリ・詳細カテゴリで絞り込んでスレッドの検索が出来る様になる
無し
- さまざまなスレッド名で検索を行い，大体の検索が出来る事を確認
英数字を入力した際に日本語が検索に引っかかったり，部分一致が出来ない場合などがあります
無し
=> スレッドの検索（カテゴリでの絞り込み検索可）

public/css/app.css, public/js/app_jquery.js, resources/js/dashboard/Get_allRow.js
- 無し
- コメントにいいねを押すと画像が表示されなかったため
- コメントにいいねを押していても画像が表示される様に修正
- いいね状態とそうではない状態の同じ部分のコードを一つに
- 無し
- コメントにいいねを押していても画像を見ることが出来る
- 無し
- いいね状態とそうでない状態で画像が表示されることを確認
- 無し
=> いいねを押している場合に画像が表示されないのを修正

.github/workflows/laravel.yml, composer.json, composer.lock
無し
- 不具合修正やセキュリティ修正の期間延長のために
- laravelを8から9にアップグレード
- 依存？パッケージの修正
- laravel9用にテスト（GitHub Actions）の修正
無し
無し
無し
- 新規登録
- 新規登録メール
- ログイン
- スレッド作成
- スレッド書き込み
- いいね・いいね取り消し
- デフォルトモード・ダークモード
以上の動作は問題無く動いているかと思います．
無し
=> laravelのアップグレード

package-lock.json
- #152
なし
- npm パッケージの更新
- 無し
無し
無し
- `npm install --update-binary --no-shrinkwrap` でインストール出来る事を確認
無し
=> npm packageの更新

bin/start-docker.sh
無し
- シェルスクリプトでコマンドを実行するコンテナが誤っていたため
- コマンドを実行するコンテナの修正
無し
無し
無し
無し
無し
=> コマンドを実行するコンテナの修正

bin/start-docker.sh
無し
- シェルスクリプトで実行するコマンドが誤っていたため
- シェルスクリプトで実行するコマンドの修正
- 無し
無し
無し
無し
無し
=> シェルスクリプトのコマンド修正

bin/start-docker.sh
無し
- シェルスクリプトで実行するコマンドが間違っていたため
- シェルスクリプトで実行するコマンドが間違っていたため修正
無し
無し
無し
- シェルスクリプトを実行し，正常に動作する事を確認
無し
=> シェルスクリプトで実行するコマンドが誤っていたため修正

public/css/app.css, public/js/app.js, public/js/app_jquery.js, resources/js/dashboard/Create_thread.js, resources/js/dashboard/Send_Row.js
- #68
- 無し
- スレッドへの書き込みボタンを押さずともを `Ctrl + Enter` で出来る様に
- スレッド作成のテキストにカーソルを合わせて `Enter` を押すとボタンを押したのと同じ処理をする
- 無し
- スレッドへの書き込みを `Ctrl + Enter` で出来る様になる
- スレッド作成ボタンを押さずともを `Enter` で出来る様に
無し
- `Ctrl + Enter` でスレッドへの書き込みが出来る事を確認
- ボタンを押さずとも `Enter` でスレッド作成が出来る事を確認
無し
=> 入力欄関連の機能追加

app/Http/Controllers/Q_and_A/Q_and_AController.php, app/Http/Controllers/dashboard/DashboardController.php, resources/views/Q_and_A/show.blade.php, resources/views/dashboard/various.blade.php, routes/web.php
- #117 
無し
- ヘルプページの作成
- ヘルプページへのリンクをダッシュボードの色々ページに追加
- ヘルプページの中身
- （将来的には）質問への回答を簡単に知ることができる様になる
無し
- 色々ページのリンクからヘルプページにアクセス出来る事を確認
無し
=> ヘルプページのベース作成・中身は後ほど

public/css/app.css, public/css/design-error.css, public/js/app.js, public/mix-manifest.json, resources/css/errors/layout.css, resources/css/errors/minimal.css, resources/views/errors/401.blade.php, resources/views/errors/403.blade.php, resources/views/errors/404.blade.php, resources/views/errors/419.blade.php, resources/views/errors/429.blade.php, resources/views/errors/500.blade.php, resources/views/errors/503.blade.php, resources/views/errors/layout.blade.php, resources/views/errors/minimal.blade.php, webpack.mix.js
- 無し
- 将来的にエラーページをカスタマイズするために
- カスタマイズ用のエラーページviewをコピー
- エラーページからデザイン部分をファイル化して移動
無し
無し
無し
- エラーページをカスタマイズして表示が出来る事を確認
無し
=> エラーページのカスタマイズ（準備）

.devcontainer/postCreateCommand.sh
- #199 
`./devcontainer/postCreateCommand.sh` が正常に動作していなかったため
- スクリプトで実行するコマンドの順序を変更
無し
- 環境構築が **正常に** 行える様になる
無し
- しっかりと `git clone` から環境構築を行い，正常に動作する事を確認しました
無し
=> postCreateCommand.shが正常に動作する様に修正

app/Http/Livewire/Dashboard/SelectThreadPages.php, app/Http/Livewire/Dashboard/Threads.php, app/Models/AccessLog.php, app/Models/AdminMenu.php, app/Models/AdminPermission.php, app/Models/ClubThread.php, app/Models/CollegeYearThread.php, app/Models/ContactAdministrator.php, app/Models/DepartmentThread.php, app/Models/Hub.php, app/Models/JobHuntingThread.php, app/Models/LectureThread.php, app/Models/Like.php, app/Models/SerializeDate.php, app/Models/ThreadCategory.php, app/Models/ThreadImagePath.php, app/Models/User.php, app/Models/UserPageTheme.php, docker/docker-compose.yml, docker/nginx/default.conf, resources/views/dashboard/header.blade.php, storage/app/public/.gitignore
- #202 
- リレーションの設定にともないカラム名を変更した影響で不具合が発生していたため
- #202 の動作確認のため
- アップロードした画像を表示出来る用にnginxの設定変更
- コンテナのタイムゾーン変更
- データベースから取得した時刻が-9:00されるのを修正
- スレッドのカテゴリ指定時にエラーが出ないように
無し
- スレッドにアップロードした画像を閲覧出来る様になる
- 書き込みされた時間を正しい時刻で知ることが出来る
- スレッドのカテゴリ選択時にエラーが出ない様になる
無し
- ユーザが作成出来る事を確認
- ログイン出来る事を確認
- 全てのカテゴリでスレッドが作成出来る事を確認
- 全てのカテゴリで書き込み・取得が出来る事を確認
- 全てのカテゴリでいいね機能が動作する事を確認
- 全てのカテゴリで `>>>1` などの返信？が出来る事を確認
- 全てのカテゴリで画像アップロードが出来る事を確認
- アクセスランキングが表示されている事を確認
- スレッドのページ移動が出来る事を確認
- マイページでテーマ変更が出来る事を確認
- お問い合わせページの内容がデータベースに保存されている事を確認
このプルリクエストにより #202 の動作確認が出来ていると判断します
=> テーブルのリレーション設定に伴う不具合の修正

.devcontainer/postCreateCommand.sh, docs/Setup/VSCode_devcontainer.md, package-lock.json
無し
- docs内のファイルにコマンドミスが見られたため
- docs内に記載されているコマンドの修正
- `npm install` に付けていたオプションなしでも動作したので遅くなる要因（おそらく）のオプションを削除
- node パッケージの脆弱性修正（npm audit fix）
無し
無し
無し
- devcontainerが動作する事を確認
無し
=> docsの修正やdevcontainerの高速化（？）

.github/workflows/slack-notify.yml
Reverts oithxs/hira-chan#219
- 「プルリクがマージした場合」の条件を削除出来ていなかったため
=> Revert "Github Notificationの実行トリガー・ブランチ変更"

.github/workflows/slack-notify.yml
=> Github Notificationの実行トリガー・ブランチ変更

.gitignore, app/Http/Kernel.php, composer.json, composer.lock, docker/app/Dockerfile, phpunit.xml, phpunit.xml.bak, tests/Feature/mypage/SelectPageThemeTest.php, tests/Unit/app/Http/Controllers/MyPage/UserController/UpdateTest.php, tests/Unit/app/Http/Controllers/Report/FormContactAdministratorController/StoreTest.php, tests/Unit/app/Services/ContactAdministratorService/StoreTest.php
なし
- laravel 10 へのアップグレード
なし
なし
なし
- スレッドが作成できることを確認
- スレッドへ書き込みができることを確認
- 画像アップロードができることを確認
- 書き込みへいいね・返信ができることを確認
なし
=> laravel10へのアップグレード

package-lock.json, package.json, public/css/app.css, public/js/app.js, tsconfig.json, webpack.mix.js
なし
- typescript を使用できるようにするため
- typescript が使用できる様に変更
- react でも typescript を使用できる様に変更
- node module の脆弱性を排除
なし
- typescriptが使用可能になる
なし
- typescript で react が動作することを確認
javascript も従来通り使用可能です
=> typescript が使用できる様に変更
