- resources/views/hub.blade.php
- resources/views/keiziban.blade.php
- resources/views/navigation-menu.blade.php
- routes/web.php
- ログイン状態でのみ，掲示板にアクセスできるように（team discussions）
- 掲示板に誰が何を書き込んだのか，（管理者が）把握できるようにするため
- ログイン状態でないと掲示板ハブ・掲示板にアクセスできないように
- ページ内のタブでダッシュボードと掲示板（ハブ）の切り替えができるように
---
---
---
---
- h1タグ等が使えないようですが，そこに関するデザインの変更は行いません
- 誰が何を書き込んだのかを保存する処理はまだ行っておりません（team discussionに追記）
- ログイン後，すぐに掲示板を利用できるようになります
- 無し
- 掲示板ハブのリンクは正常に動作するか
- 掲示板への書き込み・内容の取得は正常に動作するか
両者ともに正常に動作しました
- ログインしていない状態で掲示板（ハブ）にアクセスできるかどうか
アクセスできませんでした（正常な動作）
- 無し
> ログイン状態でないと掲示板ハブ・掲示板にアクセスできないように

- app/Actions/Fortify/CreateNewUser.php
- resources/views/auth/register.blade.php
- #13 
- #12 
- #10 
- バグ解決のため
- 入力の手間を解消するため
- 新規登録のメール入力欄で@以降の入力を不要に
- @以降を無効化する事でドメイン名のエラーを解消
- 無し
- 新規登録時に@以降の入力が不要になる（ログイン時は@以降必要）
- 無し
同じアカウントが登録されている状態・されていない状態共に，メール（学生番号）入力欄で以下のパターンを試しました
- アカウント名
- アカウント名@
- アカウント名@ドメイン名
すべての状態で正しく動作しました．
- 未登録であればドメイン名を追加してアカウント追加
- 登録済みであれば「登録されています」のメッセージを表示
- 無し
> 新規登録のメール入力エラーを解消

- app/Http/Controllers/jQuery_ajax.php
- app/Http/Controllers/keizibanCTL.php
- public/css/app.css
- public/js/Get_allRow.js
- public/js/Send_Row.js
- resources/js/Get_allRow.js
- resources/js/Send_Row.js
- resources/views/keiziban.blade.php
- #9 
- #16 
- Issueで説明が十分なため無し
- テーブルに登録される名前をログインしているユーザ名に変更
- 不要だった箇所の削除（`public/js/Get_allRow.js`, `public/js/Sned_Row.js`）
必要だと思っていたJQuery.ajaxでの値渡しが不要だったので該当箇所の削除
- ユーザ名の重複登録の解決
あくまで表示される名前をアカウントのユーザ名に固定することであるため，ここでは解決に取り組みません
- 掲示板への書き込みの際に，一々ユーザ名を入力しなくても良くなる
- アカウントとは異なるユーザ名での書き込みができなくなる
- 掲示板ページに移動し，名前の入寮欄が無いことを確認しました
- 掲示板に書き込み，ログインしているユーザ名が表示されることを確認しました
- 同じユーザ名のアカウントの場合，書き込んだユーザの判断ができなくなってしまうようです
Laravel以外ではjQuery.ajaxでのデータ渡しには削除前の方法を用いていたのですが，Laravelでは$requestを利用しているので，勝手が異なるようです．$requestの中身に何が入っているのかは未確認です
> 掲示板に書き込みした際に表示される名前をアカウントのユーザ名に固定する

- app/Actions/Fortify/CreateNewUser.php
- app/Actions/Fortify/UpdateUserProfileInformation.php
- #16 
- Issueの補足は特にありません
- 新規登録時のユーザ名にユニーク属性を追加
- 更新時のユーザ名にユニーク属性を追加
- 無し
- 無し
- ユーザ名の重複登録ができなくなる（正常な動作）
- テーブルに存在するユーザ名・テーブルに存在しないメールアドレスで新規登録を行う
- テーブルに存在するユーザ名で更新処理を実行する
両者ともにメッセージが表示され，登録・更新は実行されませんでした
ユーニーク属性を付ける際，`unique`だけではエラーが表示され，`:users`を付けると正常に動作した．`:users`の意味がよく分かりません．おそらくはテーブル名のことを言っているのかな？
> アカウントのユーザ名に一意性を持たせる

- public/js/Get_allRow.js
- resources/js/Get_allRow.js
- #6
- Issueで十分なので補足説明はありません
- 繰り返し実行する部分を関数化し，始めに実行する部分と繰り返し実行する部分に分割
無し
- 掲示板初回読み込み時の間を減らす事ができる様になる
- 無し
- 全ての掲示板の初回読み込み速度が素早くなっている事を確認した
-  無し
> 掲示板初回読み込みの時間を短縮する

- app/Models/Send.php
- #7 
- 無し
- 掲示板の入力文字列から，改行コードをを書き換えて表示するときに改行されるように
- 無し
- 掲示板書き込みの改行ができる様になる
- 無し
- 実際に掲示板に改行ありの文字列を入力してみて，改行されることを確認した
- 無し
> 掲示板に改行機能追加

- app/Http/Controllers/jQuery_ajax.php
- app/Http/Controllers/showTablesCTL.php
- app/Models/create_thread.php
- public/js/Create_thread.js
- public/mix-manifest.json
- resources/js/Create_thread.js
- resources/lang/ja.json
- resources/views/hub.blade.php
- routes/web.php
- webpack.mix.js
- #29 
- 無し
- スレッド名・作成ボタンを掲示板ハブに追加
- ボタンクリック時の処理を`resources/js/Create_thread.js`ファイルに記述（jQuery.ajax）
- `app/Http/Controllers/jQuery_ajax.php`にスレ立て用のコントローラを追記
- スレッド作成用のモデルを作成（テーブルの追加）
- スレッドの管理がしやすいように、各スレッドの情報を記録するテーブルを用意
- スレッド名・スレ立て日時の記録
- スレッド（掲示板）の作成ができる様になる
- 無し
- さまざまな名前でスレッドが作成できることを確認
- 作成したスレッドに書き込みができることを確認
スレッドの作成自体はできますが，コンソールに`/jQuery.ajax/create_thread 500 (Internal Server Error)`が出力されます
> スレッド作成機能の追加

- app/Http/Controllers/jQuery_ajax.php
- app/Http/Controllers/showTablesCTL.php
- app/Models/Get.php
- app/Models/create_thread.php
- database/migrations/2022_05_05_112244_create_hub_table.php
- resources/lang/ja.json
- resources/views/hub.blade.php
- #28 
- #29  
- 無し
- migrationで必須のテーブルを作成（テーブル名: hub）
- スレッド作成時にhubテーブルにテーブル名と作成日時を記録
- ハブで表示されるテーブル名の取得方法を変更
- ハブで各スレッドの情報を表示
- スレッド作成時にコンソールに表示されるエラーを解決
- この変更によりドキュメントに不要箇所ができたが，ここではドキュメントの修正は行わない
- 各スレッドの作成日時を知る事ができる様になる
- 無し
- スレッド作成を行い，エラーが表示されなくなることを確認しました
- スレッド作成を行い，作成日時が表示される事を確認しました
- 作成したスレッドで書き込み・表示ができる事を確認しました
- 無し
> スレッドの情報をハブに表示

- app/Http/Controllers/jQuery_ajax.php
- #32 
- なし
- スレッドの書き込みで，コメントを何も入力していない状態で書き込みボタンをクリックしても書き込みできない様にした
無し
なし
- 入力なしのコメントの書き込み（正常な動作）
- 何も入力していない状態で書き込みボタンをクリックし，書き込みができないことを確認しました
- 入力をしていれば書き込みが可能なことを確認しました
無し
> スレッドのコメントに何も入力がされていないと書き込みができない様に

- app/Http/Controllers/AccountDelete.php
- app/Models/User.php
- app/Notifications/VerifyEmailAddURL.php
- routes/web.php
- #11 
- 無し
- 送信されるメールの編集（削除用URLを送信）
- 削除用URLでアクセスされた場合該当アカウントを削除
- 削除用URLで2度以上アクセスされた場合のエラーをmiddlwareで防ぐ
- 削除用URLでアクセスされた場合welcome画面へリダイレクトする
- メール検証後，すぐさま削除用URLを無効にすること（時間経過で無効になるようです）
- 間違って自分以外のメールアドレスで登録された場合，該当アカウントを削除できる様になる（時間制限あり）
- 無し
- 削除用URLでアクセスした際にアカウントが削除されることを確認しました
- 削除用URLで複数回アクセスした際にエラーが表示さずにログイン画面へ遷移する事を確認しました
- 時間経過で無効化されるのかは検証しておりません
> 間違ったメールアドレスで登録してしまった場合の処理

- app/Models/Send.php
- #27 
- 行頭での空白が可能になることで表現の幅が増えるから
- 半角・全角スペースを表示可能に
- <>で囲まれた部分がタグとして認識されないように
- タブを半角スペース2つに
- &を置換することで特殊文字の入力によって変換されないように
- 無し
- 行頭に空白の入力が可能になる
- 特殊文字の入力によって変換が起こらなくなる（正常な動作）
- 置換対象の文字を入力して変換される事を確認した
- いくつかの特殊文字を入力して変換が起こらない事を確認した
- 入力制限（行数制限）が必要かと思います
- 空白・改行のみの入力はできない様にした方がいいかと思います
> 空白の表示・特殊文字の置換

- app/Http/Controllers/jQuery_ajax.php
- app/Http/Controllers/keizibanCTL.php
- app/Models/Like.php
- database/migrations/2022_05_09_134146_create_likes_table.php
- public/js/app_jquery.js
- resources/js/Get_allRow.js
- resources/views/hub.blade.php
- resources/views/keiziban.blade.php
- routes/web.php
- #23
- 無し
- 掲示板にいいね用ボタンを設置
- いいねを保存するテーブルを追加（マイグレーション）
- いいねを押せる数を1人・1書き込みにつき1つに制限する
- 各コメントのいいねボタンが押された回数をカウントしてテーブルに保存する
- コメントのいいねボタンが押された回数をそのコメントに表示する
- 各コメントにいいねを押すことができるようになる
- 無し
- いいねボタンを複数回クリックして，レコードが重複しないことを確認
- 複数の書き込みで同様の動作をする事を確認
- いいねの数を表示させるのにはテーブルの大きな変更が必要なため，いったんマージします
> いいね機能の追加（未完）

- resources/lang/ja.json
- resources/views/auth/login.blade.php
- resources/views/auth/register.blade.php
- resources/views/profile/update-password-form.blade.php
- #37 
無し
- 新規登録時のパスワード入力欄で，アカウントのパスワードで登録しないように注意喚起のメッセージを追加
- ログイン時のパスワード入力欄で，アカウントのパスワードを入力しないように注意喚起のメッセージを追加
- パスワード変更のformでアカウントのパスワードを入力しないように注意喚起のメッセージを追加
無し
- パスワード入力時に警告メッセージを見れるようになる
- 無し
- 新規登録時のパスワード入力欄で注意喚起メッセージが表示されることを確認
- ログイン時のパスワード入力欄で注意喚起メッセージが表示されることを確認
- パスワード変更用のformで注意喚起メッセージが表示が表示されることを確認
無し
> 大学アカウントのパスワードで登録・入力しないようにメッセージを表示

- app/Http/Kernel.php
- app/Http/Middleware/AccessGET.php
- routes/web.php
- #46 
無し
- Routeにデータ処理用URL（POSTメソッド）と同じURLのGETメソッドバージョンを登録
- URL入力でのアクセス（GETメソッド）からのアクセスには404を返すミドルウェアを追加
- 無し
- 無し
- 無し
- 全てのデータ処理用URLにアクセスして，404が表示される事を確認しました
無し
> データ処理以外からのアクセスを404にする

- resources/lang/ja.json
- resources/views/auth/login.blade.php
- resources/views/welcome.blade.php
- #57 
無し
- welcomeページからログイン・新規登録のリンクを削除
- welcomeページに掲示板ハブ・Twitter・入部（ガワだけ）・Githubへのリンクを追加
- ログインページに新規登録ページのリンクを追加　
- 入部関連のリンク・メール送信など
- HxSコンピュータ部関連のページへwelcomeページから移動する事が出来る様になる
- 無し
- 入部希望リンク以外が正常に動作する事を確認しました
ログイン・新規登録へのリンクは削除しましたが，掲示板へログインしていない状態でアクセスすると，自動的にログインページへ移動する事が出来ます．welcomeページから新規登録ページへはURLを知らなければ移動出来ないので，ログインページに新規登録ページへ移動するためのリンクを追加しています．そのため，ログイン・新規登録へのリンクは削除しても問題無しと判断しました．
> ウェルカムページの編集

- resources/views/MyPage.blade.php
- resources/views/dashboard.blade.php
- #58 
無し
- ダッシュボードにwelcomeページと同じものを配置
- 現在マイページが機能していないため，マイページ用のデザインを削除
無し
- HxS関連の各種リンクにアクセスしやすくなる
無し
- ログイン後ダッシュボードにアクセスし，デザインが変更されている事を確認
無し
> ダッシュボードのデザイン変更

- resources/views/hub.blade.php
- resources/views/keiziban.blade.php
- #67 
無し
- ハブからURLを生成する際にバックスラッシュを文字列に変換
- スレッドページで文字列からバックスラッシュに変換
無し
- スレッド名にバックスラッシュを使用可能になる
無し
- バックスラッシュが含まれるスレッド名でスレッド作成．このスレッドで書き込み・いいね機能が正常に動作することを確認
無し
> スレッド名にバックスラッシュが含まれている場合でもスレッドページに移動

- app/Http/Controllers/jQuery_ajax.php
- app/Http/Controllers/keizibanCTL.php
- app/Http/Middleware/Access_log.php
- app/Models/Get.php
- app/Models/Record_AccessLog.php
- database/migrations/2022_05_25_073001_create_access_logs_table.php
- public/js/app_jquery.js
- resources/js/Get_allRow.js
- resources/views/keiziban.blade.php
- routes/web.php
- #62
無し
- 書き込みが無いスレッドで「スレッドが存在しません」を表示させない
- 以前までの「スレッドが存在しません」表示の判定処理を削除
- `access_logs`テーブルにカラムの追加
- 保存するアクセスログにスレッド名の追加
- URLのスレッド名・スレッドIDが空の状態でも「スレッドが存在しません」を表示させる / 以前は404エラー
無し
無し
無し
- URLのスレッドIDを編集して，「スレッドが存在しません」が表示される事を確認
- アクセスログにスレッド名が保存される事を確認
- アクセスログでスレッド名・スレッドIDが何もない（URLに）状態でも保存される事を確認
無し
> 書き込みが無い状態でも，スレッドが存在していれば「スレッドが存在しません」を表示させない

- app/Http/Controllers/jQuery_ajax.php
- app/Http/Middleware/Access_log.php
- app/Models/Get.php
- app/Models/Like.php
- app/Models/Record_AccessLog.php
- app/Models/create_thread.php
- database/migrations/2022_05_05_112244_create_hub_table.php
- database/migrations/2022_05_09_134146_create_likes_table.php
- database/migrations/2022_05_25_073001_create_access_logs_table.php
- #75 
- #76 
無し
- アクセスログで保存するものをユーザIDからユーザEmailに変更
- いいねで保存するものをユーザIDからユーザEmailに変更
- hubテーブルのカラムを`timestamp`に
- hubテーブルレコード追加のクエリを見やすく書き換え
- likesテーブルのカラムの文字列がある程度決まっているものは`text`から`string`に型変更
- likesテーブルのカラムの`time`を`timestamp`に変更
無し
無し
無し
- アクセスログにユーザEmailが保存される事を確認
- いいねテーブルにユーザEmailが保存される事を確認
- スレッドを新規作成出来る事を確認
- スレッドに書き込み出来る事を確認
- いいねボタンが押せる事を確認
- いいねの取り消しが出来る事を確認
無し
> いいね・アクセスしたユーザを特定するためにユーザIDからユーザEmailに保存するものを変更

- docs/README.md
- #93 
ドキュメントファイルのリンクが間違っているため
- README.mdのリンクを修正
- Windows11の開発環境構築でメール送信を可能にする手順をついかすること
無し
無し
- README.mdのリンクにアクセスし，対象のファイルへアクセス出来る事を確認
無し
> ドキュメントのファイルリンクを修正

- .vscode/settings.json
なし
- vscodeの推奨拡張機能のポップアップを強制的に表示させるため
- .vscode/settings.json  個人設定を上書き
なし
- 設定をtrueにしている場合でも表示される
なし
開発用サーバーと個人のvscode
なし
> 推奨拡張機能のポップアップを表示させる

- app/Http/Controllers/jQuery_ajax.php
- app/Http/Middleware/IsAdmin.php
- app/Models/UserPageThemas.php
- database/migrations/2014_10_12_000000_create_users_table.php
- database/migrations/2022_06_17_115624_create_user_page_themas_table.php
- database/seeders/DatabaseSeeder.php
- database/seeders/UserPageThemasSeeder.php
- public/css/app.css
- public/js/app_jquery.js
- resources/js/SelectPageThema.js
- resources/views/MyPage.blade.php
- resources/views/dashboard.blade.php
- resources/views/hub.blade.php
- resources/views/keiziban.blade.php
- resources/views/navigation-menu.blade.php
- routes/web.php
- webpack.mix.js
無し
ユーザごとに異なるテーマでページ表示を可能にするため
- `is_admin`カラムの不具合予備軍の修正
- ユーザテーブルに表示テーマ用カラム追加
- ユーザの表示テーマ変更手段をマイページに追加
- テーマカラムを利用してデザインはこのプルリクではやらない
- マイページでテーマカラムを変更できる
無し
- 複数ユーザで異なるテーマを設定出来る事を確認
- マイページにテーマ変更用の箇所があり，そこからテーマ変更出来る事を確認
無し
> ページテーマ用にユーザテーブルにカラム追加

- .github/workflows/laravel.yml
なし
- 行う処理を減らすことで速度の高速化ができるかな〜？と思いまして
- 使わなくなった2つ目のデータベースに関する処理を削除
なし
なし
なし
- フォーク先リポジトリのGithub Actionsでテストが正常に動作することを確認
なし
> GitHub Actionsで不要なデータベースの作成をしないように

- app/Http/Controllers/jQuery_ajax.php
- app/Models/AccessLogs.php
- app/Models/AdminMenu.php
- app/Models/Hub.php
- app/Models/Likes.php
- app/Models/ThreadCategorys.php
- app/Models/ThreadImagePaths.php
- app/Models/UserPageThemas.php
- composer.json
- composer.lock
- config/image.php
- database/migrations/2022_07_09_111745_create_thread_image_paths_table.php
- database/migrations/2022_07_16_061648_change_unique_img_path_to_thread_image_paths_table.php
- public/css/app.css
- public/js/app_jquery.js
- resources/js/dashboard/Get_allRow.js
- resources/js/dashboard/Send_Row.js
- resources/views/dashboard/send-comment.blade.php
- routes/web.php
- #128 
- #141 
- 無し
- データベースに保存する日時のフォーマット変更
- 画像パス保存用のテーブル作成
- 画像アップロード機能追加（画像以外は禁止）
- アップロードされた画像を表示
- 通信データ多くなるので更新を5秒毎に変更
- 画像フォーマットを jpg に変更
- exif情報の削除
- webp への変換
- 画像のアップロード
- 無し
- 複数スレッドで画像のアップロード・表示が出来る事を確認
- 同一スレッドの異なるメッセージで異なる画像をアップロード・表示が出来る事を確認
無し
> スレッドに画像のアップロード機能追加

- resources/views/dashboard/threads.blade.php
- #144 
- 無し
- スレッドにアクセスするURL部分を特殊文字変換
無し
- `/`, `\`, `#` をスレッド名に使用出来る様になる
無し
- `/`, `\`, `#` を含んだスレッド名にアクセス出来る事を確認
無し
> スレッド名に特殊文字を使用していてもアクセス可能に修正

- app/Http/Controllers/jQuery_ajax.php
- public/css/app.css
- public/js/app_jquery.js
- resources/js/dashboard/Get_allRow.js
- resources/js/dashboard/Reply_message.js
- resources/js/dashboard/Send_Row.js
- resources/views/dashboard/send-comment.blade.php
- #104 
無し
- 書き込みの際に返信元のメッセージに移動しやすいように補助
- 閲覧の際に返信元のメッセージに移動しやすいように補助
無し
- 書き込みに対する返信がしやすくなる
- 閲覧時に返信元が確認しやすくなる
- 無し
- 書き込みの際の返信元をわかりやすくする補助が動作していることを確認
- 閲覧の際に返信元をわかりやすくする補助が動作していることを確認
- 無し
> 書き込みに返信を行いやすいように

- app/Http/Livewire/Dashboard/Threads.php
- resources/views/dashboard/threads.blade.php
無し
- スレッド一覧表示部分のソートができなくなっていたから
- ソートに使用するURLのPHPの変数名が重複していたため修正
- 使用していない処理の部分を削除
- 無し
- スレッドのソートができるようになる
- 無し
- 新作順・アクセス順にソートができることを確認
無し
> スレッドのソートができるように修正・未使用の箇所を削除

- .htaccess
- public/css/app.css
- public/js/app_jquery.js
- resources/js/dashboard/Get_allRow.js
無し
- dockerの開発環境はurlからpublicを消す事を前提とされていたから
- urlにpublicなしでも動くように `.htaccess` を追加
- publicがあっても書き込みを取得出来る様に変更
無し
- urlにpublicを含めていてもアクセス出来る様になる
無し
- 実際にdockerでの環境で書き込みを取得出来る事を確認
無し
> 現状のdocker環境構築では必要だったのでurlからpublicを消す手段追加

- package-lock.json
- package.json
無し
- 脆弱性があるnpmパッケージを使用しないため
- npmパッケージの自動アップデート
- npmパッケージの手動アップデート
- `npm run dev | prod` コマンドを使える様に
無し
無し
無し
- `npm audit` で脆弱性のあるパッケージが出ないことを確認
- `npm run dev | prod` コマンドが使用可能になっている事を確認
無し
> npmパッケージの更新

- app/Http/Middleware/Access_log.php
- composer.json
- composer.lock
- database/migrations/2022_08_08_223259_change_string_thread_name_to_access_logs_table.php
- database/migrations/2022_08_08_223317_change_string_thread_id_to_access_logs_table.php
無し
- アクセスログでnullがあるとエラーが表示されたから
- アクセスログでnullになる可能性のあるカラムでエラーにならない様に調整
- `thread_id`, `thread_name` カラムは `text` 型ほどの文字長は必要無いと思われるため `string` 型に変更
- null 許容カラムにせずともエラーがでないように出来たため nullを許容しないカラムのまま変更なし
- `thread_name`
- `thread_id`
無し
無し
- `thread_name`, `thread_id` で null を指定（urlで）したときにエラーが出力されないことを確認
無し
> アクセスログの不具合修正

- app/Http/Controllers/dashboard/ClubThreadsController.php
- app/Http/Controllers/dashboard/CollegeYearThreadsController.php
- app/Http/Controllers/dashboard/DepartmentThreadsController.php
- app/Http/Controllers/dashboard/JobHuntingThreadsController.php
- app/Http/Controllers/dashboard/LectureThreadsController.php
- app/Http/Controllers/dashboard/LikesController.php
- app/Http/Controllers/dashboard/ThreadsController.php
- public/js/app_jquery.js
- resources/js/dashboard/Get_allRow.js
- resources/views/dashboard/messages.blade.php
- resources/views/dashboard/show.blade.php
- #103 
- #154
- 通信の負荷軽減
- スレッド書き込み取得を1秒につき1回に変更
- すでに表示されている書き込みから追加された場合のみ追加のデータ（書き込み）取得
- いいねボタンの連打防止
- #103 
- 管理者ユーザによる削除・復元が行われていれば全ての書き込みを更新
- 過去の書き込みが更新されなくなったので，過去の書き込みをコピペのために選択していても更新に伴って選択が解除されるという事が無くなる -> コピペがしやすくなる
- 1度の通信で扱うデータ量が少なくなったので通信量を減らす事が出来る
- いいねボタン連打によって2以上のいいねカウントを押すことが出来なくなる（正常な動作）
- 過去の書き込みを選択した状態を更新頻度以上の時間継続出来事を確認
- いいねボタンを連打しても1度しかカウントされない事を確認
無し
> メッセージの取得改良

- app/Http/Controllers/dashboard/DashboardController.php
- app/Http/Livewire/Dashboard/Header.php
- app/Http/Livewire/Dashboard/Messages.php
- app/Http/Livewire/Dashboard/Rankings.php
- app/Http/Livewire/Dashboard/SelectThreadPages.php
- app/Http/Livewire/Dashboard/SendComment.php
- app/Http/Livewire/Dashboard/Threads.php
- app/Http/Livewire/Dashboard/Various.php
- resources/views/dashboard/rankings.blade.php
- resources/views/dashboard/various.blade.php
- #169 
無し
- 週間アクセスランキングをランキングモジュールに移動
- アクセスランキングと週間アクセスランキングをタブで切り替え出来る様に
無し
- ランキングと週間アクセスランキングをタブで切り替えられる様になる
- アクセスランキングと週間アクセスランキングを同時に見る事が出来なくなる
- アクセスランキングと週間アクセスランキングが問題無く表示され，タブで切り替えられる事を確認しました
次は
- #117 
を行います
> 週間アクセスランキングの移動

- app/Http/Controllers/dashboard/ClubThreadsController.php
- app/Http/Controllers/dashboard/CollegeYearThreadsController.php
- app/Http/Controllers/dashboard/DashboardController.php
- app/Http/Controllers/dashboard/DepartmentThreadsController.php
- app/Http/Controllers/dashboard/JobHuntingThreadsController.php
- app/Http/Controllers/dashboard/LectureThreadsController.php
- app/Http/Controllers/dashboard/ThreadsController.php
- app/Http/Controllers/dashboard/not_logged_in/ClubThreadsController.php
- app/Http/Controllers/dashboard/not_logged_in/CollegeYearThreadsController.php
- app/Http/Controllers/dashboard/not_logged_in/DepartmentThreadsController.php
- app/Http/Controllers/dashboard/not_logged_in/JobHuntingThreadsController.php
- app/Http/Controllers/dashboard/not_logged_in/LectureThreadsController.php
- app/Http/Controllers/dashboard/not_logged_in/ThreadsController.php
- app/Http/Kernel.php
- app/Http/Livewire/Dashboard/Header.php
- app/Http/Livewire/Dashboard/Messages.php
- app/Http/Livewire/Dashboard/Rankings.php
- app/Http/Livewire/Dashboard/SelectThreadPages.php
- app/Http/Livewire/Dashboard/SendComment.php
- app/Http/Livewire/Dashboard/Threads.php
- app/Http/Livewire/Dashboard/Various.php
- app/Http/Middleware/Access_log.php
- resources/views/dashboard/messages.blade.php
- resources/views/dashboard/send-comment.blade.php
- resources/views/dashboard/show.blade.php
- resources/views/layouts/app.blade.php
- resources/views/navigation-menu.blade.php
- routes/web.php
- tests/Feature/dashboard/AuthenticationTest.php
- tests/Feature/mypage/SelectPageThemaTest.php
- #87 
無し
- ログインしていない状態でもダッシュボードに移動できるように
- ログインしていない状態でもスレッドに移動できるように
- ログインしていない状態ではスレッドに書き込みができないように
- ログインしていない状態ではいいね機能を利用できないように
- ログインしていない状態ではスレッドを作成できないように
- ログインしていない状態での動作が変わったのでテストの調整
- 無し
- ログインしていない状態でもダッシュボードにアクセスできるようになる
- ログインしていない状態でもスレッドを見ることができるようになる
- 無し
- ログインした状態での動作が正常なことを確認
- ログインしていない状態でもダッシュボードにアクセスできることを確認
- ログインしていない状態でもスレッドにアクセスできることを確認
- ログインしていない状態ではスレッドに書き込みができないことを確認
- ログインしていない状態ではいいね機能を利用できないことを確認
- ログインしていない状態ではスレッドを作成できないことを確認
この影響でセキュリティ対策が甘くなっている可能性が十二分にあるため，何か見つければ連絡いただけるとありがたいです．
> ログインしていない状態でスレッドにアクセスできるように

- app/Http/Kernel.php
- app/Http/Middleware/MustAuthVerified.php
- resources/views/dashboard/messages.blade.php
- resources/views/dashboard/send-comment.blade.php
- resources/views/navigation-menu.blade.php
- routes/web.php
- #177 
- 不具合修正
- ログイン状態かつメール未確認であればメール確認を行うページに移動させるミドルウェアを作成
- メール確認出来ていなければログイン状態でページを表示させない
- 上記のミドルウェアをダッシュボードページとQ & A ページに適応
- ページ内でログインチェックを行っていた箇所でメール確認済みであるかどうかも条件追加
なし
- ログイン時にメール確認が出来ていなければメール確認ページに移動される様になる
- メール確認なしではログインが出来なくなる
- ログイン出来ていない状態でもダッシュボードにアクセス出来る事を確認
- 新規登録時にメール確認ページに移動する事を確認
- メール確認出来ていなければログイン状態でもダッシュボードを表示されない事を確認（メール確認ページに移動される）
無し
> ログイン時にはメール確認済みとなるように変更

- app/Admin/Controllers/General/ThreadController.php
- app/Admin/Extensions/Tools/GeneralUser.php
- app/Admin/routes.php
- app/Http/Controllers/dashboard/ThreadsController.php
- app/Http/Controllers/dashboard/not_logged_in/ThreadsController.php
- app/Http/Livewire/Dashboard/Messages.php
- app/Http/Livewire/Dashboard/Threads.php
- app/Models/AdminPermissions.php
- app/Models/Hub.php
- database/migrations/2022_08_22_183914_add_is_enabled_to_hub_table.php
- database/seeders/AdminInstallSeeder.php
- database/seeders/AdminMenuSeeder.php
- database/seeders/AdminPermissionsSeeder.php
- database/seeders/DatabaseSeeder.php
- resources/lang/ja.json
- #167 
無し
- スレッドが有効か無効かを判断するために `hub.is_enabled` を追加
- 無効であればHubに表示しないように
- 向こうであれば有効時と同じURLでアクセスしても閲覧・書き込みをできないように
- 有効・無効を切り替えるための場所をlaravel-adminの `General.Threads` に作成
- laravel-adminの `Admin.Permission` にSeederでレコード追加
無し
無し
無し
- 管理者画面で有効無効が切り替えられることを確認
- 無効になっていればスレッド一覧に表示されないことを確認
- 無効であればアクセスできないことを確認
- 無効であれば書き込みできないことを確認
無し
> 管理者によるスレッド削除機能

- app/Http/Controllers/Dashboard/ClubThreadController.php
- app/Http/Controllers/Dashboard/CollegeYearThreadController.php
- app/Http/Controllers/Dashboard/DepartmentThreadController.php
- app/Http/Controllers/Dashboard/JobHuntingThreadController.php
- app/Http/Controllers/Dashboard/LectureThreadController.php
- app/Http/Controllers/Dashboard/NotLoggedIn/ClubThreadController.php
- app/Http/Controllers/Dashboard/NotLoggedIn/CollegeYearThreadController.php
- app/Http/Controllers/Dashboard/NotLoggedIn/DepartmentThreadController.php
- app/Http/Controllers/Dashboard/NotLoggedIn/JobHuntingThreadController.php
- app/Http/Controllers/Dashboard/NotLoggedIn/LectureThreadController.php
- app/Http/Controllers/Dashboard/NotLoggedIn/ThreadsController.php
- app/Http/Controllers/Dashboard/ThreadsController.php
- app/Models/ClubThread.php
- app/Models/CollegeYearThread.php
- app/Models/DepartmentThread.php
- app/Models/Hub.php
- app/Models/JobHuntingThread.php
- app/Models/LectureThread.php
- app/Models/User.php
- database/migrations/2022_09_05_223619_drop_column_thread_id_to_thread_tables.php
- database/migrations/2022_09_05_223952_drop_column_user_name_to_thread_tables.php
- database/migrations/2022_09_05_224103_drop_column_user_email_to_thread_tables.php
- database/migrations/2022_09_05_224726_drop_column_is_validity_to_thread_tables.php
- database/migrations/2022_09_05_224946_add_column_hub_id_to_thread_tables.php
- database/migrations/2022_09_05_225120_add_column_user_id_to_thread_tables.php
- public/js/app_jquery.js
- resources/js/dashboard/Get_allRow.js
- resources/views/dashboard/threads.blade.php
- #183 
- #186 
`club_threads`, `college_year_threads`, `department_threads`, `job_hunting_threads`, `lecture_threads` => `threads`
- `threads` テーブルに外部キー `hub_id`, `user_id` カラムを追加
- `threads` テーブルの `thread_id`, `user_name`, `user_email`, `is_validity` カラム削除
- Eloquent: Relationships・変更したカラムにデータ追加 が出来る様に Model の変更
- 書き込みの表示・書き込みが出来る様に Controller などを変更
- 未ログインとログイン済みのコントローラで同じ箇所があったためクラスの継承を用いる
無し
無し
無し
- ログインしていない状態で `threads` テーブルの書き込みが表示出来る事を確認
- ログインしている状態で `threads` テーブルの書き込みが表示出来る事を確認
- スレッドに書き込み・画像のアップロードが出来る事を確認
- `contact_administrators`
- `hub`
- `likes`
- `thread_categorys`
- `thread_image_paths`
- `users`
- `user_page_themas`
> 各カテゴリのスレッドテーブルのリレーション・その活用

- app/Http/Middleware/AccessLog.php
- resources/views/dashboard/threads.blade.php
- #190 
- アクセスログでスレッドが保存出来ていなかったため
- （週間・）アクセスランキングが常に0となるようになっていたため
- スレッド表示部分で閲覧回数が表示されていなかったため
- アクセスログでスレッドを保存出来る様に修正
- スレッド表示部分の閲覧回数が正しく表示される様に修正
無し
- （週間・）アクセスランキングを見られるようになる
- スレッド表示部分で閲覧回数を見られるようになる
無し
- （週間・）アクセスランキングが見られることを確認
- スレッド表示部分で閲覧回数が見られる事を確認
無し
> アクセスログの取得・表示の修正

- app/Http/Controllers/Report/FormContactAdministratorController.php
- app/Models/ContactAdministrator.php
- app/Models/User.php
- database/migrations/2022_09_15_231034_add_column_user_id_to_contact_administrators_table.php
- database/migrations/2022_09_15_231432_drop_column_report_email_to_contact_administrators_table.php
- #183 
- #186 
- `contact_administrators` テーブルに外部キー `user_id` を追加・`report_email` カラムの削除
- Eloquent: Relationships を利用・変更したカラムにデータを挿入，出来る様にモデルの変更
- 管理者に報告が出来る様にコントローラの変更
無し
無し
無し
- 報告ページで報告する事でデータベースに報告内容が保存される事を確認
- `hub`
- `likes`
- `thread_categorys`
- `thread_image_paths`
- `users`
- `user_page_themas`
> "contact_administrators" テーブルのリレーション・その活用

- .devcontainer/postCreateCommand.sh
- .env.example
- .github/workflows/laravel.yml
- docker/app/Dockerfile
- docker/docker-compose.yml
- docker/mariadb/Dockerfile
- docker/mysql/Dockerfile
無し
- デフォルトのアプリ名の変更するため
- 本番環境で使用するデータベースがMysqlからMariaDBへと変更になったため
- セットアップ後にスレッドにアップロードされた画像が取得出来なかったため
- Laravelのデプロイに必要なシステム要件を満たせていなかったため
- `.env.example` でアプリ名を `hira-chan` に変更
- `docker` フォルダ内のファイルを変更し，開発で使用するDBイメージをMariaDBに変更
- devcontaienrの始めに実行されるスクリプトでスレッドにアップロードされた画像を保存するディレクトリを作成
- 同スクリプトでlaravel-adminで必要だったコマンド部分を削除
- laravelフレームワークのサーバ要件を満たすように `hira-chan_app` のDockerfileを変更
無し
- devcontainerでのセットアップ直後にスレッドにアップロードされた画像を取得出来る様に
無し
- devcontainerのセットアップが正常に実行出来る事を確認
- セットアップ後直後にスレッドに，アップロードされた画像の取得が出来る事を確認
無し
> 開発用セットアップの変更

- .devcontainer/postCreateCommand.sh
- docker/app/Dockerfile
無し
- 開発用コンテナでgitコマンドの補完が行われず不便だったため
- git補完のためのシェルダウンロード
- シェルの適応
無し
- コンテナ内でTabキーによりgitコマンドの補完が出来る様になる
無し
- コンテナ内でTabキーによりgitコマンドの補完が出来る事を確認
無し
> 開発用コンテナでgitコマンドの補完が行われるように変更

- app/Models/User.php
無し
- 管理画面でEmailの検証が行えなかったから
- Model の User ファイルで，`fillable` の項目に `email_verified_at` を追加
無し
- ユーザのEmail検証が管理画面で行える様になる
無し
- 管理画面でユーザのEmail検証および検証の取り消しが出来る事を確認
無し
> 管理画面でユーザのEmail検証が行えなかったのを修正

- .github/workflows/slack-notify.yml
無し
- fork先からのプルリクエストに対しても通知が行くように（期待通り通知が行くかは不明）
- `Github Notification` の実行トリガーをプルリクエストのマージから，対象ブランチへのpushに変更
- 本番環境の通知が来ても混乱するとおもわれるので，対象ブランチから `main` を削除
無し
- `develop` ブランチへのマージ（push）時にslackへ通知が行く様になる（はず）
無し
無し
期待通り動作をしなければ，マージの取り消しを行います．
> Github Notificationの実行トリガー・ブランチ変更

- app/Filament/Resources/UserResource.php
- #223 
無し
- 管理画面のusersリソースの変更可能箇所を増やす．（fillableにある全ての属性）
- 管理画面のusersリソースでidを表示する（デフォルトでは「toggleable(isToggledHiddenByDefault: true)」を使用して非表示にする）
- 管理画面のusersリソースの参考リンクを変更する
- 管理画面のusersリソースで取得出来る全ての属性を取得
- 管理画面のusersリソースで取得出来た全ての属性で検索を可能にする
無し
- 管理画面のusersリソースでほぼ全ての属性を見られる様になる
- 管理画面のusersリソースでほぼ全ての属性でレコードを検索出来る様になる
無し
- 取得出来る全ての属性を取得し，管理画面で表示出来ている事を確認
- 取得出来る全ての属性で検索が出来る事を確認
無し
> 管理画面のusersリソースで全ての属性を閲覧・検索出来る様に変更

- app/Filament/Resources/HubResource.php
無し
- （ほぼ）全ての属性を見る事が出来る様に
- 個々の目的のレコードを素早く発見出来る様にするため
- 取得出来る全ての属性を取得し，管理画面で表示
- 取得出来る全ての属性で検索が出来る様に変更
無し
- 管理画面のhubリソースで（ほぼ）全ての属性を確認することが出来る様になる
- 管理画面のhubリソースで確認出来る属性で検索が出来る様になる
無し
- 取得出来る全ての属性を取得し，管理画面で表示出来ている事を確認
- 取得出来る全ての属性で検索が出来る事を確認
無し
> 管理画面で取得出来る全てのhubリソースを取得し，その属性で検索が出来る様に変更

- app/Models/AccessLog.php
- app/Models/ClubThread.php
- app/Models/CollegeYearThread.php
- app/Models/ContactAdministrator.php
- app/Models/DepartmentThread.php
- app/Models/Hub.php
- app/Models/JobHuntingThread.php
- app/Models/LectureThread.php
- app/Models/Like.php
- app/Models/ThreadCategory.php
- app/Models/ThreadImagePath.php
- app/Models/User.php
- app/Models/UserPageTheme.php
なし
- モデルでキャストするカラム名が異なっていたため修正
- モデルでキャストするカラムとして `update_at` となっていたものを `updated_at` へ変更 
なし
なし
なし
なし
なし
> キャストするカラム名が間違っていたため修正

- docker/app/Dockerfile
- tests/Unit/app/Http/Controllers/Dashboard/ThreadImagePathController/StoreTest.php
- tests/Unit/app/Http/Controllers/Dashboard/ThreadsController/StoreTest.php
- #232 
- #233 
なし
- webp形式の画像を扱えるようにDockerfileを編集
- webp形式の画像をアップロードしたときのテストを修正
- 扱えない形式の画像をアップロードされたときの処理を追加すること
- webp形式の画像をアップロードできるようになる
なし
- webp形式の画像をアップロードできることを確認
なし
> スレッドにwebp形式の画像をアップロード可能にする

- app/Http/Kernel.php
- app/Http/Middleware/AccessLog.php
- app/Models/AccessLog.php
- database/migrations/2022_12_31_212013_drop_column_session_id_to_access_logs_table.php
- database/migrations/2022_12_31_212036_drop_column_uri_to_access_logs_table.php
- routes/web.php
- tests/Feature/Dashboard/AuthenticationTest.php
- tests/Feature/Dashboard/Thread/AccessLogTest.php
- tests/Unit/app/Http/Middleware/AccessLog/HandleTest.php
- #172 
- #205 
なし
- `access_logs` テーブルの `session_id`, `uri` カラムを削除
- スレッドアクセス時のみにアクセスログを保存するように変更
- 前回と同じスレッドにアクセスした際にはアクセスログを保存しないように変更
- 存在しないスレッドにアクセスした際にはアクセスログを保存せず，404ページを表示する
- 存在しないスレッドにアクセスした際に「このスレッドは存在しません」などの専用メッセージを表示すること
- 存在しないスレッドにアクセスした際に，書き込みが何も表示されないスレッドが表示されるのではなく，404ページへ移動することができる
なし
- スレッド以外へアクセスした際にアクセスログが保存されないことを確認
- スレッドアクセス時にF5などでリロードした際にアクセスログが増えないことを確認
- 存在しないスレッドにアクセスした際には専用メッセージを表示せずとも，404ページを表示するだけで十分かと思います．
> アクセスログをスレッドアクセスした際だけに保存するように変更

- app/Consts/Tables/HubConst.php
- app/Consts/Tables/ThreadSecondaryCategoryConst.php
- app/Http/Controllers/Dashboard/HubController.php
- app/Repositories/HubRepository.php
- app/Repositories/ThreadSecondaryCategoryRepository.php
- app/Services/HubService.php
- tests/Support/AssertSame/Tables/HubTrait.php
- tests/Support/PostTestTrait.php
- tests/Support/Random.php
- tests/Unit/app/Http/Controllers/Dashboard/HubController/StoreTest.php
- tests/Unit/app/Repositories/HubRepository/StoreTest.php
- tests/Unit/app/Repositories/ThreadPrimaryCategoryRepository/GetThreadSecondaryCategoryHasManyTest.php
- tests/Unit/app/Repositories/ThreadSecondaryCategoryRepository/NameToId.php
- tests/Unit/app/Services/HubService/StoreTest.php
なし
- 細かく分けた方が管理・更新がしやすいため
- hubテーブル関連の定数で取得できなかったものを修正
- HubRepositoryにスレッドを作成するメソッドを追加
- ThreadSecondaryCategoryConstの大枠カテゴリに属する詳細カテゴリを取得できる定数名を変更
- 詳細カテゴリテーブル関連の定数クラスに詳細カテゴリ一覧の定数を追加
- thread_secondary_categorys テーブル関連のクエリを入れるリポジトリクラスを作成
- hubテーブル関連のビジネスロジック（サービスクラス）の作成
- HubControllerの処理を分割したリポジトリクラスとサービスクラスを利用するように変更
なし
なし
なし
- テスト作成
- スレッドが作成できることを確認
- 作成したスレッドへ書き込み・画像アップロード・書き込みの取得ができることを確認
なし
> HubControllerをサービスクラスとリポジトリクラスに分割

- app/Consts/Tables/LikeConst.php
- app/Http/Controllers/Dashboard/LikeController.php
- app/Repositories/LikeRepository.php
- app/Repositories/ThreadRepository.php
- app/Services/LikeService.php
- app/Services/ThreadService.php
- tests/Support/AssertSame/Tables/LikeTrait.php
- tests/Support/LikeTestTrait.php
- tests/Unit/app/Http/Controllers/Dashboard/LikeController/DestroyTest.php
- tests/Unit/app/Http/Controllers/Dashboard/LikeController/StoreTest.php
- tests/Unit/app/Repositories/LikeRepository/CountLikeTest.php
- tests/Unit/app/Repositories/LikeRepository/DestroyTest.php
- tests/Unit/app/Repositories/LikeRepository/StoreTest.php
- tests/Unit/app/Repositories/ThreadRepository/FindIdTest.php
- tests/Unit/app/Repositories/ThreadRepository/FindTest.php
- tests/Unit/app/Services/LikeService/CountLikeTest.php
- tests/Unit/app/Services/LikeService/DestroyTest.php
- tests/Unit/app/Services/LikeService/StoreTest.php
- tests/Unit/app/Services/ThreadService/ThreadIdToForeignKeyTest.php
- tests/Unit/app/Services/ThreadService/ThreadIdToModelTest.php
- #245 
- 1ファイルにまとめるには量が多いため
- 細かく分けたほうが管理・更新がしやすいため
- LikeControllerで使用していたEloquentモデルのクエリを各テーブルごとに分けた，リポジトリクラスを作成
- LikeControllerの ↑ 以外の処理を入れたサービスクラスを作成
- ThreadRepositoryに特定の書き込みを取得するメソッド・そのIDを取得するメソッドを追加
- likesテーブル関連の定数クラスにカラム一覧の配列を追加
なし
なし
なし
- 単体テスト作成
- 書き込みにいいね・いいねの取り消しができることを確認
なし
> LikeControllerをサービスクラスとリポジトリクラスに分割

- tests/Feature/laravel/ApiTokenPermissionsTest.php
- tests/Feature/laravel/AuthenticationTest.php
- tests/Feature/laravel/BrowserSessionsTest.php
- tests/Feature/laravel/CreateApiTokenTest.php
- tests/Feature/laravel/DeleteAccountTest.php
- tests/Feature/laravel/DeleteApiTokenTest.php
- tests/Feature/laravel/EmailVerificationTest.php
- tests/Feature/laravel/PasswordConfirmationTest.php
- tests/Feature/laravel/PasswordResetTest.php
- tests/Feature/laravel/ProfileInformationTest.php
- tests/Feature/laravel/RegistrationTest.php
- tests/Feature/laravel/TwoFactorAuthenticationSettingsTest.php
- tests/Feature/laravel/UpdatePasswordTest.php
なし
- ファイルまでのパスとネームスペースが異なっていたため
- tests/Feature/laravel フォルダ内のネームスペースを `Tests/Feature/_laravel` -> `Tests\Feature/laravel` に変更
なし
なし
なし
- 変更したファイルのテストが `php artisan test` で実行されることを確認
なし
> 機能テスト，laravelフォルダ内のネームスペースがフォルダ名と異なっているのを修正
